version: '3'

networks:
  test_network:
    driver: bridge

services:
  oidc:
    container_name: oidc
    image: quay.io/keycloak/keycloak:24.0.1-0
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_URL: http://oidc:8080
      # KC_LOG_LEVEL: DEBUG
      # KEYCLOAK_IMPORT: /opt/keycloak/realm-export.json
    volumes:
      - type: bind
        source: ./oidc/realm-export.json
        target: /opt/keycloak/realm-export.json
        read_only: true
    command:
      - start-dev

  tyk:
    container_name: tyk
    image: tykio/tyk-gateway
    ports:
      - "8000:8000"
    depends_on:
      - tyk-redis
    environment:
      TYK_LOGLEVEL: DEBUG
    volumes:
      - ./tyk/apps:/opt/tyk-gateway/apps
      - ./tyk/tyk.conf:/opt/tyk-gateway/tyk.conf
      - ./tyk/policies:/opt/tyk-gateway/policies
      - ./tyk/middleware:/opt/tyk-gateway/middleware

  tyk-redis:
    container_name: tyk-redis
    image: redis:latest
    ports:
      - "6379:6379"
  api:
    build: ./backend
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/api
    command: bash -c "poetry run python manage.py runserver 0.0.0.0:8000"
    #networks:
    #  - test_network
  api2:
    build: ./backend2
    ports:
      - "8002:8000"
    volumes:
      - ./backend2:/api
    command: bash -c "poetry run python manage.py runserver 0.0.0.0:8000"
    #networks:
    #  - test_network
  web:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/front
      - /front/node_modules
    command: bash -c "npm run dev-docker"
    networks:
      - test_network
    environment:
      API_URL: localhost:8001
      KEYCLOAK_URL: localhost:8080
  nextjs:
    build: ./nextjs
    container_name: nextjs
    hostname: nextjs
    ports:
      - 4000:3000
    env_file:
      - ./config/nextjs/.env
  bff:
    build: bff
    container_name: bff
    hostname: bff
    command: bash -c "npm start"
    volumes:
      - ./bff:/app
      - /app/node_modules
    ports:
      - 4001:3000


